/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMiPessoas = new javax.swing.JMenuItem();
        jMiBancos = new javax.swing.JMenuItem();
        jMiContas = new javax.swing.JMenuItem();
        jMiTipos = new javax.swing.JMenuItem();
        jMiFluxo = new javax.swing.JMenuItem();
        jMiSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDpPrincipalLayout = new javax.swing.GroupLayout(jDpPrincipal);
        jDpPrincipal.setLayout(jDpPrincipalLayout);
        jDpPrincipalLayout.setHorizontalGroup(
            jDpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jDpPrincipalLayout.setVerticalGroup(
            jDpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDpPrincipal)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenu1.setText("Controles");

        jMiPessoas.setText("Pessoas");
        jMiPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiPessoasActionPerformed(evt);
            }
        });
        jMenu1.add(jMiPessoas);

        jMiBancos.setText("Bancos");
        jMiBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiBancosActionPerformed(evt);
            }
        });
        jMenu1.add(jMiBancos);

        jMiContas.setText("Contas");
        jMiContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiContasActionPerformed(evt);
            }
        });
        jMenu1.add(jMiContas);

        jMiTipos.setText("Tipos");
        jMiTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiTiposActionPerformed(evt);
            }
        });
        jMenu1.add(jMiTipos);

        jMiFluxo.setText("Fluxo");
        jMiFluxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiFluxoActionPerformed(evt);
            }
        });
        jMenu1.add(jMiFluxo);

        jMiSair.setText("Sair");
        jMiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMiSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentos");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMiSairActionPerformed

    private void jMiBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiBancosActionPerformed
        try {
            CadBancos bk = new CadBancos();
            bk.setVisible(true);
            //ct.setPosicao();
            jDpPrincipal.add(bk);
            bk.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jMiBancosActionPerformed

    private void jMiPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiPessoasActionPerformed
        try {
            CadPessoas cp = new CadPessoas();
            cp.setVisible(true);
            //ct.setPosicao();
            jDpPrincipal.add(cp);
            cp.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jMiPessoasActionPerformed

    private void jMiContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiContasActionPerformed
        try {
            CadContas ct = new CadContas();
            ct.setVisible(true);
            //ct.setPosicao();
            jDpPrincipal.add(ct);
            ct.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jMiContasActionPerformed

    private void jMiTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiTiposActionPerformed
        try {
            CadTipos ct = new CadTipos();
            ct.setVisible(true);
            //ct.setPosicao();
            jDpPrincipal.add(ct);
            ct.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jMiTiposActionPerformed

    private void jMiFluxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiFluxoActionPerformed
        try {
            CadFluxo cf = new CadFluxo();
            cf.setVisible(true);
            //ct.setPosicao();
            jDpPrincipal.add(cf);
            cf.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jMiFluxoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDpPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMiBancos;
    private javax.swing.JMenuItem jMiContas;
    private javax.swing.JMenuItem jMiFluxo;
    private javax.swing.JMenuItem jMiPessoas;
    private javax.swing.JMenuItem jMiSair;
    private javax.swing.JMenuItem jMiTipos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
